[package]
name = "zellij-rust-analyzer"
version = "0.1.0"
edition = "2021"
description = "Zellij plugin for rust-analyzer"
authors = [
  "Heath Stewart (https://github.com/heaths)",
]
license = "MIT"
repository = "https://github.com/heaths/zellij-rust-analyzer"
readme = "README.md"

[[bin]]
name = "zellij_rust_analyzer"
path = "src/main.rs"
test = false

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
zellij-tile = "0.44.3"
